name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/shell/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -c "import nltk; nltk.download('vader_lexicon'); nltk.download('stopwords'); nltk.download('punkt')"
        
    - name: Create .env file
      run: |
        echo "APP_NAME=Mental Health Support" > .env
        echo "APP_VERSION=0.1.0" >> .env
        echo "DEBUG=True" >> .env
        echo "SECRET_KEY=test-secret-key" >> .env
        echo "ALGORITHM=HS256" >> .env
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
        echo "AWS_ACCESS_KEY_ID=fakeAccessKeyId" >> .env
        echo "AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey" >> .env
        echo "AWS_REGION=us-east-1" >> .env
        echo "DYNAMODB_ENDPOINT=http://localhost:8000" >> .env
        echo "S3_BUCKET_NAME=test-bucket" >> .env
        echo "OPENAI_API_KEY=fake-openai-key" >> .env
        echo "GOOGLE_API_KEY=fake-google-key" >> .env
        
    - name: Test with pytest
      run: |
        mkdir -p reports
        pytest backend/tests/ --cov=backend --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
